services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_tasks"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    env_file:
      - .env.docker
    working_dir: /home/appuser
    depends_on:
      db:
        condition: service_healthy
    command: ["/usr/local/bin/go-tasks"]
    ports:
      - "8080:8080"

volumes:
  pgdata: