name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    name: Build & Test Go API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Verify Build
        run: go build -o main cmd/main.go

      - name: Run Tests
        run: go test -v ./...
